template = "https://github.com/giellalt/template-lang-und"
rev_id = 263
template_sha = "1bc24707891f274cd9b2690b032d9864fa1205f5"

[replacements]
__GLOTTOLOG_ID__ = "nucl1667"
__REPO__ = "lang-aym"
__UND2C__ = "ay"
__UNDEFINED__ = "Aymara"
__UND__ = "aym"
